#!/bin/bash
DIR=`readlink $0`
cd `dirname $DIR`

. ./utils.sh
log "pam_script_auth"
. ./cryptoloop.sh

if [ ! -e /home/athen/home/$PAM_USER/private.key ] ; then
  mount_home "$PAM_USER" "$PAM_AUTHTOK"
  ./unspool-mail.sh "$PAM_USER" &
  disown
else
  log "already loggin in, succeeding"
  exit 0
fi 
# CONFIG_FILE: /var/run/dovecot/config
# DOVECOT_PRESERVE_ENVS: TZ DEBUG_OUTOFMEM
# DOVECOT_HOSTNAME: e36124758327
# DOVECOT_CHILD_PROCESS: 1
# SERVICE_COUNT: 1
# PROCESS_MIN_AVAIL: 0
# LOG_SERVICE: 1
# PAM_USER: vmail
# PAM_RHOST: 127.0.0.1
# SSL_SOCKET_COUNT: 0
# IDLE_KILL: 60
# PAM_AUTHTOK: vmail
# PROCESS_LIMIT: 100
# PAM_OLDAUTHTOK: 
# GENERATION: 8
# PAM_SERVICE: dovecot
# PAM_TTY: dovecot
# PAM_TYPE: auth
# SOCKET_NAMES: auth-worker	
# CLIENT_LIMIT: 1
# DOVECOT_HOSTDOMAIN: e36124758327
# SOCKET_COUNT: 1
